# Generated by Django 6.0.3 on 2026-03-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='celebrities/'),
        ),
    ]
