# Generated by Django 6.0.3 on 2026-03-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_category_profile_tag_celebrity_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='tags',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celebrities.category'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
